### ISSUE TITLE
Publish Confirmation Timeout

### ISSUE THREAD

**Issue by istrau2** [houseofcat/turbocookedrabbit#24]
config:
```
Seasoning:
    EncryptionConfig:
      Enabled: false
      Type: aes
      TimeConsideration: 1
      Threads: 2
    CompressionConfig:
      Enabled: false
      Type: gzip
    PoolConfig:
      URI: amqps://user:password@instancename.rmq2.cloudamqp.com/virtualhost
      Heartbeat: 1800
      ConnectionTimeout: 5
      SleepOnErrorInterval: 1
      MaxConnectionCount: 10
      MaxCacheChannelCount: 10
    ConsumerConfigs:
      order_event_sync_ib:
        ConsumerName: order.event.sync.ib
        Enabled: true
        QueueName: order.event.sync.ib
        AutoAck: true
        Exclusive: true
        NoWait: true
        SleepOnErrorInterval: 1
        SleepOnErrorInterval: 1
    PublisherConfig:
      AutoAck: true
      SleepOnErrorInterval: 1
      SleepOnErrorInterval: 1
      PublishTimeOutInterval: 5
      MaxRetryCount: 5
  Topology:
    Exchanges:
    - Name: request.fix.itiviti
      Type: "fanout"
      PassiveDeclare: false
      Durable: true
      AutoDelete: false
      InternalOnly: false
      NoWait: true
    Queues:
    - Name: egress.itiviti
      PassiveDeclare: false
      Durable: true
      AutoDelete: false
      Exclusive: false
      NoWait: true
    QueueBindings:
    - QueueName: egress.itiviti
      ExchangeName: request.fix.itiviti
      NoWait: true
      NoWait: true
```

code:
```
func NewRabbitMQProvider(cfg *RabbitMQConfig, applicationName string) (*RabbitMQProvider, error) {
	cp, err := tcr.NewConnectionPool(cfg.Seasoning.PoolConfig)
	if err != nil {
		return nil, util.WrapError(err)
	}

	t := tcr.NewTopologer(cp)
	if err != nil {
		return nil, util.WrapError(err)
	}
	err = t.BuildTopology(&cfg.Topology, false)
	if err != nil {
		return nil, util.WrapError(err)
	}

	return &RabbitMQProvider{
		seasoning: cfg.Seasoning,
		connPool:  cp,
	}, nil
}

func (p *RabbitMQProvider) Publish(letter *tcr.Letter, skipReceipt bool, publishReceiptHandler func(*tcr.PublishReceipt)) {
	publisher := p.ProvidePublisher()
	p.handlerChan <- publishReceiptIDHandler{
		handler:  publishReceiptHandler,
		letterID: letter.LetterID.String(),
	}
	publisher.PublishWithConfirmationTransient(letter, 10)
}

letter := &tcr.Letter{
		LetterID: id,
		Body:     []byte(nos.ToMessage().String()),
		Envelope: &tcr.Envelope{
			Exchange:     "request.fix.itiviti",
			RoutingKey:   "egress.itiviti",
			ContentType:  "text/plain",
			Mandatory:    true, // put this message on at least one queue, if not, send it back
			Immediate:    true, // send immediately or not at all
			Priority:     0,    // not relevant
			DeliveryMode: 1,    // do not store messages to disc to resend in case of server crash, storing in disc affects latency and would cause messages to be asyncronously sent
		},
	}

	b.rabbitMQProvider.Publish(letter, false, func(r *tcr.PublishReceipt) {
		if r.Success {
			fmt.Println(fmt.Sprintf("letter %s published successfully", letter.LetterID.String()))
		} else {
			fmt.Println(fmt.Sprintf("letter %s errored on publish with: %s", letter.LetterID.String(), r.Error.Error()))
		}
	})
```

seeing the following error message:

> letter 3183b158-2a7e-11ec-a460-acde48001122 errored on publish with: publish confirmation for LetterID: 3183b158-2a7e-11ec-a460-acde48001122 wasn't received in a timely manner (10ms) - recommend retry/requeue
